import Head from "next/head";
import Link from "next/link";
import { ReactNode } from "react";
import { Navbar, NavbarLogo } from "./layout.styles";
import User from "./User";

type DashboardLayoutProps = {
	children: ReactNode;
	home?: boolean;
};

export default function Layout({ children, home }: DashboardLayoutProps) {
	return (
		<div className="App">
			<Head>
				<title>Mando Nextjs</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/mando.svg" />
				{/* <link
					rel="stylesheet"
					href="https://cdnjs.cloudflare.com/ajax/libs/antd/3.16.2/antd.css"
				/> */}
				{/* <!--GOOGLE FONTS for Inter--> */}
				<link rel="preconnect" href="https://fonts.googleapis.com" />
				<link
					rel="preconnect"
					href="https://fonts.gstatic.com"
					//  crossorigin
				/>
				<link
					href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@700&family=Inter:wght@100;200;300;400;500;700&display=swap"
					rel="stylesheet"
				/>
				{/*<!-- FONT AWESOME --> */}
				<script
					src="https://kit.fontawesome.com/856c5d3b66.js"
					//crossorigin="anonymous"
				></script>
				<meta
					name="viewport"
					content="user-scalable=no, width=device-width, initial-scale=1, maximum-scale=1"
				/>
			</Head>
			{!home && (
				<div className="backToHome">
					<Link href="/">
						<a>← Back to home</a>
					</Link>
				</div>
			)}
			<Navbar className="navbar navbar-light d-flex justify-content-between">
				<Link className="navbar-brand navbar-logo" href="/">
					<NavbarLogo>MANDO</NavbarLogo>
				</Link>
				<User />
			</Navbar>
			<main>{children}</main>

			<footer className="footer">
				<p>made at Harbour.Space</p>
			</footer>
		</div>
	);
}
